package com.loan.achintya.data.model;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Lob;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
public class User {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private int uid;
	private String fname;
    private String lname;
    private String username;
    private String password;
    private String toEmail;
    @Lob
    private byte[] profilePhoto;
    @Lob
    private byte[] signature;
    private String designation;
    //add email,fname,lname(autogenerated username password implement in srvicimpl),userProfilePhoto
           }
